const day01 = require("./D01");
const day02 = require("./D02");
const day03 = require("./D03");
const day04 = require("./D04");
const day05 = require("./D05");
const day06 = require("./D06");
const day07 = require("./D07");
const day08 = require("./D08");
const day09 = require("./D09");
const day10 = require("./D10");
const day11 = require("./D11");
const day12 = require("./D12");


(() => {
    console.log("Let's crack some riddles");
    console.log("Day 1: ");
    day01();
    console.log("Day 2: ");
    day02();
    console.log("Day 3: ");
    day03();
    console.log("Day 4: ");
    day04();
    console.log("Day 5: ");
    day05();
    console.log("Day 6: ");
    day06();
    console.log("Day 7: ");
    day07();
    console.log("Day 8: ");
    day08();
    console.log("Day 9: ");
    day09();
    console.log("Day 10: ");
    day10();
    console.log("Day 11: ");
    day11();
    console.log("Day 12: ");
    day12();
})();